[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  SKIP_PREFLIGHT_CHECK = "true"
  ESLINT_NO_DEV_ERRORS = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  CI = "false"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
