[build]
  command = "npm install && cd client && npm install && npm run build"
  publish = "client/build"
  functions = "netlify/functions"

[build.environment]
  SKIP_PREFLIGHT_CHECK = "true"
  ESLINT_NO_DEV_ERRORS = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  CI = "false"
  NODE_VERSION = "16"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "visitor"]}

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Community service redirects
[[redirects]]
  from = "/api/community/*"
  to = "/.netlify/functions/community/:splat"
  status = 200
