[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.setup.env]
SKIP_PREFLIGHT_CHECK = "true"
ESLINT_NO_DEV_ERRORS = "true"
DISABLE_ESLINT_PLUGIN = "true"
CI = "false"

[phases.install]
cmds = [
  "npm install",
  "cd client && npm install",
  "cd ../server && npm install",
  "cd ../community-service && npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]

[start]
cmd = "npm start"
